{% set name = "flytekitplugins-modin" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flytekitplugins-modin-{{ version }}.tar.gz
  sha256: ea25725b1bf352e4eb680999376c785a0aa148c7d6520dbe8d033f9a2c6abd60

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - flytekit >=1.0.0b3,<1.2.0
    - fsspec
    # Change version after it is available on conda-forge
    # - grpcio <=1.43.0
    - grpcio <=1.46.3
    # Change version after it is available on conda-forge
    # - grpcio-status <=1.43.0
    - grpcio-status <=1.46.3
    - modin >=0.13.0
    - ray-default

test:
  imports:
    - flytekitplugins.modin
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/flytekitplugins-modin/
  summary: Modin plugin for flytekit
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  description: |
    Modin plugin for Flytekit: `{{ name }}`

    PyPI: [https://pypi.org/project/flytekitplugins-modin/](https://pypi.org/project/flytekitplugins-modin/)

  doc_url: https://github.com/flyteorg/flytekit/tree/master/plugins
  dev_url: https://github.com/flyteorg/flytekit/tree/master/plugins/flytekit-modin

extra:
  recipe-maintainers:
    - sugatoray
